### PR TITLE
Exception handling

### PR DESCRIPTION
**Pull request by terevos**
Some python exception handling for when Reddit API acts strangely or we encounter some other kind of issue.

### CODE REVIEW

**Comment by Nokeo08** [comment]
Who did you close this? Looked good to me.

**Comment by terevos** [comment]
I'll fix it up and submit again tomorrow. I failed to notice your exception
handling you already put in. And I can't do ratelimiting that way but the
other exception handling can go there.

Thanks.

**Comment by terevos** [comment]
You had a good idea. Just needed to handle a few more things and also a
catch all.


On another note,
I just blocked Andrew. Not sure that guy's issue but I want no part of any
drama.

**Comment by terevos** [comment]
Alrighty - I have a new PR that makes a little more use of your exception handling in failable.py

I could not add the ratelimiting there because I'd have to pass all kinds of variables and whatnot.

Thanks.
***@***.***

**Comment by terevos** [comment]
And another one that fixes when people call the bot from nureddit.  

https://github.com/Nokeo08/standardsbot/pull/27 

***@***.***

**Comment by terevos** [comment]
Ok, I revamped my branch to just have the changes that should be in there.  https://github.com/Nokeo08/standardsbot/pull/28 

I'll try not to double-stack branches in the future for github.

Thanks.
***@***.***

**Pull request closed without merging**
